// ─── Seed data pulled from SIF_2026-27.pdf (Seven Hills College of Pharmacy) ─
// Used for prototype / demo only

export const SEED_FACULTY = [
  {
    id: 'f001',
    name: 'Dr. Mudduluru Niranjan Babu',
    councilNo: 'BH-P-23-18028',
    department: 'pharmacognosy',
    designation: 'hoi',
    qualification: { ug: 'B.Pharm', pg: 'M.Pharm', phd: 'Ph.D' },
    experienceYears: 27,
    dateOfJoining: '2007-05-09',
    employmentType: 'full-time',
    spcRegistration: 'valid',
    aebas: false,
    status: 'verified',
    courses: ['bpharm', 'mpharm'],
    salaryApr_Sep: 1463808,
  },
  {
    id: 'f002',
    name: 'Dr. Jyothi Basini',
    councilNo: 'BH-P-25-59225',
    department: 'pharmacology',
    designation: 'professor',
    qualification: { ug: 'B.Pharm', pg: 'M.Pharm', phd: 'Ph.D' },
    experienceYears: 31.8,
    dateOfJoining: '2018-10-01',
    employmentType: 'full-time',
    spcRegistration: 'valid',
    aebas: false,
    status: 'verified',
    courses: ['bpharm'],
    salaryApr_Sep: 707772,
  },
  {
    id: 'f003',
    name: 'Dr. Satheesh Kumar G',
    councilNo: 'BH-P-24-1847319343',
    department: 'pharm_chemistry',
    designation: 'assoc_prof',
    qualification: { ug: 'B.Pharm', pg: 'M.Pharm', phd: 'Ph.D' },
    experienceYears: 16,
    dateOfJoining: '2018-10-03',
    employmentType: 'full-time',
    spcRegistration: 'valid',
    aebas: false,
    status: 'verified',
    courses: ['bpharm'],
    salaryApr_Sep: 861720,
  },
  {
    id: 'f004',
    name: 'Pavan Kumar V',
    councilNo: 'BH-P-24-0918356760',
    department: 'pharmaceutics',
    designation: 'assoc_prof',
    qualification: { ug: 'B.Pharm', pg: 'M.Pharm', phd: null },
    experienceYears: 11.6,
    dateOfJoining: '2017-04-10',
    employmentType: 'full-time',
    spcRegistration: 'valid',
    aebas: false,
    status: 'qual_review',   // Assoc. Prof. — Ph.D pending
    courses: ['bpharm', 'mpharm'],
    salaryApr_Sep: 576720,
  },
  {
    id: 'f005',
    name: 'DIVYA LAKSHMIPATHI',
    councilNo: 'BH-P-24-2112744734',
    department: 'pharmaceutics',
    designation: 'assoc_prof',
    qualification: { ug: 'B.Pharm', pg: 'M.Pharm', phd: null },
    experienceYears: 10,
    dateOfJoining: '2015-09-14',
    employmentType: 'full-time',
    spcRegistration: 'valid',
    aebas: false,
    status: 'verified',
    courses: ['bpharm'],
    salaryApr_Sep: 595776,
  },
  {
    id: 'f006',
    name: 'HARIKRISHNA M',
    councilNo: 'BH-P-24-1147133573',
    department: 'pharmaceutics',
    designation: 'assoc_prof',
    qualification: { ug: 'B.Pharm', pg: 'M.Pharm', phd: null },
    experienceYears: 7,
    dateOfJoining: '2016-07-01',
    employmentType: 'full-time',
    spcRegistration: 'pending',
    aebas: false,
    status: 'qual_review',
    courses: ['bpharm'],
    salaryApr_Sep: 595776,
  },
  {
    id: 'f007',
    name: 'PUSHPA KUMARI B',
    councilNo: 'BH-P-23-34210',
    department: 'pharmacology',
    designation: 'professor',
    qualification: { ug: 'B.Pharm', pg: 'M.Pharm', phd: 'Ph.D' },
    experienceYears: 17.6,
    dateOfJoining: '2023-02-16',
    employmentType: 'full-time',
    spcRegistration: 'valid',
    aebas: false,
    status: 'verified',
    courses: ['bpharm', 'mpharm'],
    salaryApr_Sep: 1124802,
  },
  {
    id: 'f008',
    name: 'G MALLIKARJUNA',
    councilNo: 'BH-P-25-46375',
    department: 'pharmacology',
    designation: 'assoc_prof',
    qualification: { ug: 'B.Pharm', pg: 'M.Pharm', phd: null },
    experienceYears: 11.4,
    dateOfJoining: '2015-09-14',
    employmentType: 'full-time',
    spcRegistration: 'valid',
    aebas: false,
    status: 'verified',
    courses: ['bpharm', 'mpharm'],
    salaryApr_Sep: 513720,
  },
  {
    id: 'f009',
    name: 'A. REKHA DEVI',
    councilNo: 'BH-P-23-34506',
    department: 'pharmaceutics',
    designation: 'assoc_prof',
    qualification: { ug: 'B.Pharm', pg: 'M.Pharm', phd: 'Ph.D' },
    experienceYears: 12.5,
    dateOfJoining: '2022-08-01',
    employmentType: 'full-time',
    spcRegistration: 'valid',
    aebas: false,
    status: 'verified',
    courses: ['bpharm', 'mpharm'],
    salaryApr_Sep: 612720,
  },
  {
    id: 'f010',
    name: 'Saravanakumar Kasimedu',
    councilNo: 'BH-P-24-1501164767',
    department: 'pharmaceutics',
    designation: 'assoc_prof',
    qualification: { ug: 'B.Pharm', pg: 'M.Pharm', phd: 'Ph.D' },
    experienceYears: 19,
    dateOfJoining: '2022-06-20',
    employmentType: 'full-time',
    spcRegistration: 'valid',
    aebas: false,
    status: 'verified',
    courses: ['bpharm', 'mpharm'],
    salaryApr_Sep: 913368,
  },
  {
    id: 'f011',
    name: 'Chandrasekar R',
    councilNo: 'BH-P-24-0321107819',
    department: 'pharm_chemistry',
    designation: 'assoc_prof',
    qualification: { ug: 'B.Pharm', pg: 'M.Pharm', phd: null },
    experienceYears: 15,
    dateOfJoining: '2017-04-03',
    employmentType: 'full-time',
    spcRegistration: 'valid',
    aebas: false,
    status: 'verified',
    courses: ['bpharm'],
    salaryApr_Sep: 515220,
  },
  {
    id: 'f012',
    name: 'Venkatrao Pasupuleti',
    councilNo: 'BH-P-24-0991927367',
    department: 'pharmaceutics',
    designation: 'professor',
    qualification: { ug: 'B.Pharm', pg: 'M.Pharm', phd: 'Ph.D' },
    experienceYears: 2.8,
    dateOfJoining: '2023-05-01',
    employmentType: 'full-time',
    spcRegistration: 'valid',
    aebas: false,
    status: 'verified',
    courses: ['bpharm'],
    salaryApr_Sep: 642744,
  },
  {
    id: 'f013',
    name: 'Prasanna Raju Yalavarthi',
    councilNo: 'BH-P-25-52229',
    department: 'pharmaceutics',
    designation: 'professor',
    qualification: { ug: 'B.Pharm', pg: 'M.Pharm', phd: 'Ph.D' },
    experienceYears: 28.3,
    dateOfJoining: '2024-10-14',
    employmentType: 'full-time',
    spcRegistration: 'valid',
    aebas: false,
    status: 'verified',
    courses: ['bpharm', 'mpharm'],
    salaryApr_Sep: 474792,
  },
  {
    id: 'f014',
    name: 'NAGESWARA RAO T',
    councilNo: 'BH-P-24-2129583613',
    department: 'pharm_chemistry',
    designation: 'professor',
    qualification: { ug: 'B.Pharm', pg: 'M.Pharm', phd: 'Ph.D' },
    experienceYears: 16,
    dateOfJoining: '2022-12-01',
    employmentType: 'full-time',
    spcRegistration: 'valid',
    aebas: false,
    status: 'verified',
    courses: ['bpharm'],
    salaryApr_Sep: 642744,
  },
];

export const SEED_NON_TEACHING_COUNTS = {
  lab_technician:  5,
  lab_assistant:   8,
  office_supt:     1,
  accountant:      1,
  store_keeper:    1,
  computer_operator: 1,
  office_staff_1:  1,
  office_staff_2:  2,
  peon:            1,   // Short by 1 — deliberate demo deficiency
};
